// Competency taxonomy for mapping challenges to skills / duties
export const COMPETENCIES = {
  INVESTIGATION: 'investigation', // mismatches, reconciliation, checksum, diff
  FLOW_MAPPING: 'flow-mapping',   // lineage, DAG, dependency, partition
  API_VALIDATION: 'api-validation', // API schema, pagination, parsing, contracts
  TRANSFORMATION_QUALITY: 'transformation-quality', // SCD, FX, tier mapping, masking
  AUTOMATION: 'automation', // rules engines, profiler, SLA monitors
  CLOUD_TOOLS: 'cloud-tools', // partition pruning, S3 tagging, access control
  MONITORING_ALERTING: 'monitoring-alerting', // freshness, spikes, nulls, late arrivals
  ANOMALY_DETECTION: 'anomaly-detection', // statistical, z-score, spikes, duplicates
  COMMUNICATION: 'communication', // postmortem, escalation, collaboration
  PERFORMANCE_OPTIMIZATION: 'performance-optimization' // query tuning, pruning
} as const;

export type Competency = typeof COMPETENCIES[keyof typeof COMPETENCIES];

// Helper tagging interface (non-intrusive augmentation)
export interface ChallengeTagMap { [challengeId: number]: Competency[] }

export const challengeCompetencies: ChallengeTagMap = {
  // NOTE: Challenge IDs can overlap across domains (conceptual/sql/python); mapping is by numeric id only.
  1: [COMPETENCIES.INVESTIGATION, COMPETENCIES.CLOUD_TOOLS],
  2: [COMPETENCIES.INVESTIGATION, COMPETENCIES.FLOW_MAPPING],
  3: [COMPETENCIES.INVESTIGATION],
  4: [COMPETENCIES.TRANSFORMATION_QUALITY],
  5: [COMPETENCIES.CLOUD_TOOLS, COMPETENCIES.PERFORMANCE_OPTIMIZATION],
  6: [COMPETENCIES.API_VALIDATION, COMPETENCIES.MONITORING_ALERTING],
  7: [COMPETENCIES.FLOW_MAPPING],
  8: [COMPETENCIES.FLOW_MAPPING, COMPETENCIES.MONITORING_ALERTING],
  9: [COMPETENCIES.INVESTIGATION, COMPETENCIES.MONITORING_ALERTING],
  10: [COMPETENCIES.COMMUNICATION],
  11: [COMPETENCIES.TRANSFORMATION_QUALITY, COMPETENCIES.FLOW_MAPPING],
  12: [COMPETENCIES.COMMUNICATION, COMPETENCIES.AUTOMATION],
  13: [COMPETENCIES.AUTOMATION, COMPETENCIES.TRANSFORMATION_QUALITY],
  14: [COMPETENCIES.API_VALIDATION, COMPETENCIES.TRANSFORMATION_QUALITY],
  15: [COMPETENCIES.MONITORING_ALERTING, COMPETENCIES.ANOMALY_DETECTION],
  16: [COMPETENCIES.COMMUNICATION],
  18: [COMPETENCIES.TRANSFORMATION_QUALITY],
  19: [COMPETENCIES.FLOW_MAPPING, COMPETENCIES.AUTOMATION],
  20: [COMPETENCIES.INVESTIGATION, COMPETENCIES.AUTOMATION],
  21: [COMPETENCIES.INVESTIGATION],
  22: [COMPETENCIES.PERFORMANCE_OPTIMIZATION],
  23: [COMPETENCIES.PERFORMANCE_OPTIMIZATION, COMPETENCIES.MONITORING_ALERTING],
  24: [COMPETENCIES.FLOW_MAPPING],
  25: [COMPETENCIES.INVESTIGATION],
  26: [COMPETENCIES.TRANSFORMATION_QUALITY],
  27: [COMPETENCIES.TRANSFORMATION_QUALITY, COMPETENCIES.AUTOMATION],
  28: [COMPETENCIES.TRANSFORMATION_QUALITY, COMPETENCIES.AUTOMATION],
  29: [COMPETENCIES.TRANSFORMATION_QUALITY, COMPETENCIES.INVESTIGATION],
  30: [COMPETENCIES.CLOUD_TOOLS],
  31: [COMPETENCIES.TRANSFORMATION_QUALITY, COMPETENCIES.AUTOMATION],
  32: [COMPETENCIES.TRANSFORMATION_QUALITY, COMPETENCIES.INVESTIGATION],
  33: [COMPETENCIES.MONITORING_ALERTING, COMPETENCIES.ANOMALY_DETECTION],
  34: [COMPETENCIES.PERFORMANCE_OPTIMIZATION, COMPETENCIES.CLOUD_TOOLS],
  35: [COMPETENCIES.TRANSFORMATION_QUALITY, COMPETENCIES.INVESTIGATION],
  36: [COMPETENCIES.AUTOMATION, COMPETENCIES.TRANSFORMATION_QUALITY],
  37: [COMPETENCIES.MONITORING_ALERTING],
  38: [COMPETENCIES.MONITORING_ALERTING, COMPETENCIES.ANOMALY_DETECTION],
  39: [COMPETENCIES.ANOMALY_DETECTION, COMPETENCIES.AUTOMATION]
};
